#train.yaml
num_classes: 1

model:
  weights: models/pretrained/yolo11n.pt

train:
  data_yaml: configs/data.yaml
  epochs: 2
  img_size: 320
  batch_size: 16
  lr: 0.001
  optimizer: AdamW
  weight_decay: 0.0005
  project: runs
  name: yolov11_sku110

mlflow:
  experiment_name: yolov11-sku110
